#!/bin/bash
rm plik
a=0
b=0
c=0
x=0
y=0
z=0
while [[ $a -lt 10 ]]
do
	while [[ $b -lt 10 ]]
	do
		while [[ $c -lt 10 ]]
		do
			while [[ $x -lt 1 ]]
			do
					while [[ $y -lt 10 ]]
					do
						while [[ $z -lt 10 ]]
						do
							echo "ipv4-c$a$b$c-was$x$y$z-ix.1.oca.nflxvideo.net" >> netflix-block.txt
							let "z += 1"
						done
						let "z = 0"
						let "y += 1"
					done
					let "y = 0"
					let "x += 1"
				done
				let "x = 0"
			let "c += 1"
		done
		let "c = 0"
		let "b += 1"
	done
	let "b = 0"
	let "a += 1"
done
